---
- name: Install commons tools
  hosts: all
  become: true
  tasks:
    - name: update
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 86400       # One day
    - name: apt get install
      apt:
        pkg:
          - htop
          - glances
          - emacs
          - git
          - unzip
          - vim
          - dos2unix
