---
# https://artifacthub.io/packages/helm/atlassian-data-center/bitbucket
- name: Kubernetes Atlassian BitBucket Server
  hosts: localhost
  gather_facts: false

  vars:
    force: false
    bitbucket_app: my-bitbucket
    bitbucket_helm_chart_ref: atlassian-data-center/bitbucket
    bitbucket_helm_chart_repo_url: https://atlassian.github.io/data-center-helm-charts
    bitbucket_helm_chart_version: 1.8.1
    bitbucket_namespace: bitbucket
    state: "present"
    status_job: "{{ 'Deploy' if state == 'present' else 'Remove' }}"

  pre_tasks:
    - name: Assert required vars are defined
      assert:
        that:
          - cert_manager_issuer | length > 0
          - state in ["absent","present"]
          - bitbucket_pwd | string | length > 6
          - bitbucket_username | length > 0
          - bitbucket_db_username | length > 0
          - bitbucket_db_pwd | string | length > 0
          - bitbucket_email | length > 0
          - bitbucket_dns | length > 0

    - name: Required Python Library
      pip:
        name:
          - kubernetes

  tasks:
    - name: Enable HELM repo for BitBucket
      kubernetes.core.helm_repository:
        name: atlassian-data-center
        repo_url: "{{ bitbucket_helm_chart_repo_url }}"

    - name: Ensure {{ bitbucket_namespace }} namespace is present
      kubernetes.core.k8s:
        name: "{{ bitbucket_namespace }}"
        kind: Namespace
      when: state == "present"

    - name: "{{ status_job }} BitBucket"
      kubernetes.core.helm:
        name: "{{ bitbucket_app }}"
        chart_ref: "{{ bitbucket_helm_chart_ref }}"
        chart_version: "{{ bitbucket_helm_chart_version }}"
        update_repo_cache: true
        release_values: "{{ lookup('template', 'kubernetes-templates/atlassian/bitbucket/bitbucket.values.yaml.j2') | from_yaml }}"
        release_namespace: "{{ bitbucket_namespace }}"
        release_state: "{{ state }}"
        force: "{{ force | bool }}"

    - name: Apply manifests from templates
      kubernetes.core.k8s:
        template:
          - path: kubernetes-templates/atlassian/bitbucket/certificate.yaml.j2
          - path: kubernetes-templates/atlassian/bitbucket/ingress_route.yaml.j2
        namespace: "{{ bitbucket_namespace }}"
        apply: "{{ state == 'present' }}"
        state: "{{ state }}"
