---
- name: Kubernetes Jenkins
  hosts: localhost
  gather_facts: false

  vars:
    force: false
    jenkins_helm_chart_ref: jenkins/jenkins
    jenkins_helm_chart_repo_url: https://charts.jenkins.io
    jenkins_helm_chart_version: 4.2.6
    jenkins_namespace: jenkins
    jenkins_path: /var/jenkins_home
    jenkins_plugins:
      - kubernetes:3743.v1fa_4c724c3b_7
      - workflow-aggregator:590.v6a_d052e5a_a_b_5
      - git:4.14.3
      - configuration-as-code:1569.vb_72405b_80249
    jenkins_updater_account: jenkins-updater
    staging_namespace: staging
    state: "present"
    status_job: "{{ 'Deploy' if state == 'present' else 'Remove' }}"

  pre_tasks:
    - name: Assert required vars are defined
      assert:
        that:
          - cert_manager_issuer | length > 0
          - state in ["absent","present"]
          - jenkins_dns | length > 0

    - name: Required Python Library
      pip:
        name:
          - kubernetes

  tasks:
    - name: Enable HELM repo for jenkins
      kubernetes.core.helm_repository:
        name: jenkins
        repo_url: "{{ jenkins_helm_chart_repo_url }}"

    - name: Ensure {{ jenkins_namespace }} namespace is present
      kubernetes.core.k8s:
        name: "{{ jenkins_namespace }}"
        kind: Namespace
      when: state == "present"

    - name: "{{ status_job }} Jenkins"
      kubernetes.core.helm:
        name: jenkins
        chart_ref: "{{ jenkins_helm_chart_ref }}"
        chart_version: "{{ jenkins_helm_chart_version }}"
        update_repo_cache: true
        release_values: "{{ lookup('template', 'kubernetes-templates/jenkins/jenkins.values.yaml.j2') | from_yaml }}"
        release_namespace: "{{ jenkins_namespace }}"
        release_state: "{{ state }}"
        force: "{{ force | bool }}"

    - name: Create Staging namespace
      kubernetes.core.k8s:
        name: "{{ staging_namespace }}"
        kind: Namespace
      when: state == "present"

    - name: Apply manifests from templates
      kubernetes.core.k8s:
        template:
          - path: kubernetes-templates/jenkins/role.yaml.j2
          - path: kubernetes-templates/jenkins/role_binding.yaml.j2
          - path: kubernetes-templates/jenkins/service_account.yaml.j2
          - path: kubernetes-templates/jenkins/certificate.yaml.j2
          - path: kubernetes-templates/jenkins/ingress_route.yaml.j2
        apply: "{{ state == 'present' }}"
      when: state == "present"
