---
- name: Kubernetes pgAdmin4
  hosts: localhost
  gather_facts: false

  vars:
    force: false
    pgadmin_helm_chart_repo_url: https://helm.runix.net
    pgadmin_helm_chart_ref: runix/pgadmin4
    pgadmin_helm_chart_version: 1.13.1
    pgadmin_image_tag: 6.14
    pgadmin_namespace: pgadmin
    state: present

  pre_tasks:
    - name: Assert Required variables are defined
      assert:
        that:
          - pgadmin_pwd | string | length > 0
          - pgadmin_email | length > 0
    - name: Required Python Library
      pip:
        name:
          - kubernetes>=12.0.0 # for kubernetes
  tasks:
    - name: Add pgAdmin Helm Chart repo
      kubernetes.core.helm_repository:
        name: runix
        repo_url: '{{ pgadmin_helm_chart_repo_url }}'

    - name: Kubernetes pgAdmin namespace
      kubernetes.core.k8s:
        name: '{{ pgadmin_namespace }}'
        kind: Namespace
      when: state == "present"

    - name: Deploy pgAdmin from helm
      kubernetes.core.helm:
        name: pgadmin4
        chart_ref: '{{ pgadmin_helm_chart_ref }}'
        chart_version: '{{ pgadmin_helm_chart_version }}'
        update_repo_cache: true
        release_values:
          image:
            tag: "{{ pgadmin_image_tag }}"
          env:
            email: "{{ pgadmin_email }}"
            password: "{{ pgadmin_pwd | string }}"
        release_namespace: '{{ pgadmin_namespace }}'
        release_state: '{{ state }}'
        force: '{{ force | bool }}'