# https://github.com/ansible/awx-operator/blob/devel/.helm/starter/README.md
- name: Playbook to deploy AWX operator on a kubernetes cluster
  hosts: localhost
  gather_facts: false

  vars:
    force: false
    state: present
    awx_admin: Admin
    awx_external_database: false
    awx_operator_helm_chart_ref: awx-operator/awx-operator
    awx_operator_helm_chart_version: 1.1.3
    awx_operator_helm_chart_repo_url: https://ansible.github.io/awx-operator/
    awx_operator_namespace: awx-operator
    awx_postgres_database: awx
    awx_postgres_host: awx-postgres.postgres.svc.cluster.local
    awx_postgres_port: 5432
    status_job: "{{ 'Deploy' if state == 'present' else 'Remove' }}"

  pre_tasks:
    - name: Assert required vars are defined
      assert:
        that:
          - state in ["absent","present"]
          - awx_postgres_username | length > 0
          - awx_postgres_pwd | string | length > 0

  tasks:
    - name: Enable HELM repo for AWX-operator
      kubernetes.core.helm_repository:
        name: awx-operator
        repo_url: "{{ awx_operator_helm_chart_repo_url }}"

    - name: Ensure {{ awx_operator_namespace }} namespace is present
      kubernetes.core.k8s:
        name: "{{ awx_operator_namespace }}"
        kind: Namespace
      when: state == "present"

    - name: "{{ status_job }} AWX-operator"
      kubernetes.core.helm:
        name: my-awx-operator
        chart_ref: "{{ awx_operator_helm_chart_ref }}"
        chart_version: "{{ awx_operator_helm_chart_version }}"
        update_repo_cache: true
        release_values: "{{ lookup('template', 'kubernetes-templates/operator/awx/awx_operator.values.yaml.j2') | from_yaml }}"
        release_namespace: "{{ awx_operator_namespace }}"
        release_state: "{{ state }}"
        force: "{{ force | bool }}"
