---
- name: Kubernetes Harbor
  hosts: localhost
  gather_facts: false

  vars:
    force: false
    harbor_helm_chart_ref: harbor/harbor
    harbor_helm_chart_repo_url: https://helm.goharbor.io
    harbor_helm_chart_version: 1.11.0
    harbor_namespace: harbor
    state: "present"
    status_job: "{{ 'Deploy' if state == 'present' else 'Remove' }}"

  pre_tasks:
    - name: Assert required vars are defined
      assert:
        that:
          - cert_manager_issuer | length > 0
          - state in ["absent","present"]
          - harbor_admin_pwd | string | length > 6
          - harbor_dns | length > 0

    - name: Required Python Library
      pip:
        name:
          - kubernetes

  tasks:
    - name: Enable HELM repo for Harbor
      kubernetes.core.helm_repository:
        name: harbor
        repo_url: "{{ harbor_helm_chart_repo_url }}"

    - name: Ensure {{ harbor_namespace }} namespace is present
      kubernetes.core.k8s:
        name: "{{ harbor_namespace }}"
        kind: Namespace
      when: state == "present"

    - name: "{{ status_job }} Harbor"
      kubernetes.core.helm:
        name: harbor
        chart_ref: "{{ harbor_helm_chart_ref }}"
        chart_version: "{{ harbor_helm_chart_version }}"
        update_repo_cache: true
        release_values: "{{ lookup('template', 'kubernetes-templates/harbor/harbor.values.yaml.j2') | from_yaml }}"
        release_namespace: "{{ harbor_namespace }}"
        release_state: "{{ state }}"
        force: "{{ force | bool }}"

    - name: Apply manifests from templates
      kubernetes.core.k8s:
        template:
          - path: kubernetes-templates/harbor/certificate.yaml.j2
          - path: kubernetes-templates/harbor/ingress_route.yaml.j2
        namespace: "{{ harbor_namespace }}"
        apply: "{{ state == 'present' }}"
        state: "{{ state }}"
